version: '3.1'
services:
  stats-server:
    container_name: ewm-stats
    build: ./statistic
    ports:
      - 9090:9090
    expose:
      - 9090
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5433/ewm_stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command: -p 9090

  stats-db:
    container_name: ewm_stats_db
    image: postgres:14-alpine
    ports:
      - 5433:5433
    expose:
      - 5433
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command: -p 5433

  ewm-service:
    container_name: ewm-service
    build: ./ewm-core
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_core
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STATSERV_URL=http://ewm-stats:9090
    command: -p 8080

  ewm-db:
    container_name: ewm_service_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_core
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
